# SPDX-FileCopyrightText: 2025 Steffen Vogel <post@steffenvogel.de>
# SPDX-License-Identifier: Apache-2.0

version = 1

[[annotations]]
path = ["flake.lock", "go.sum", "**/*.md", "**/*.json", "**/*.m3u8", "charts/cfac/templates/NOTES.txt", "charts/cfac/templates/_helpers.tpl"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Steffen Vogel <post@steffenvogel.de>"
SPDX-License-Identifier = "Apache-2.0"
